[ieee]
name = "IEEE"
desc = "电气与电子工程师协会"

[iec]
name = "IEC"
desc = "国际电工(技术)委员会"

[ietf]
name = "IETF"
desc = "国际互联网工程任务组"

[iso]
name = "ISO"
desc = "国际标准化组织"

[itu]
name = "ITU"
desc = "国际电信联盟，简称国际电联"
